openapi: 3.0.0
info:
  contact:
    email: api@circulodecredito.com.mx
  description: "<p>La API de FICO® Score determina la probabilidad de incumplimiento\
    \ de un acreditado en los próximos doce meses. A mayor puntaje de score, menor\
    \ es el riesgo.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png'\
    \ height='70' width='270'/></p><br/>"
  license:
    name: Derechos reservados Circulo de Crédito 2020
    url: http://www.circulodecredito.com.mx
  termsOfService: https://developer.circulodecredito.com.mx/terms-use
  title: FICO® Score
  version: 1.0.0
servers:
- url: https://services.circulodecredito.com.mx/v2/ficoscore
paths:
  /:
    post:
      deprecated: false
      description: ""
      operationId: /
      parameters:
      - description: Firma generada con la llave privada
        explode: false
        in: header
        name: x-signature
        required: true
        schema:
          type: string
        style: simple
      - description: ConsumerKey obtenido desde el portal de desarrolladores
        explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - description: Usuario de Círculo de Crédito
        explode: false
        in: header
        name: username
        required: true
        schema:
          type: string
        style: simple
      - description: Contraseña de Círculo de Crédito
        explode: false
        in: header
        name: password
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestScoreDG"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseScore"
          description: OK
        "204":
          content: {}
          description: NO CONTENT
        "400":
          content:
            application/json:
              example:
                errores:
                - codigo: "400"
                  mensaje: "El campo [nombre_campo] es requerido"
                - codigo: "400"
                  mensaje: El código postal no corresponde al estado.
                - codigo: "400.4"
                  mensaje: Petición incorrecta el x-signature es requerido.
              schema:
                $ref: "#/components/schemas/Errores"
          description: BAD REQUEST
        "401":
          content:
            application/json:
              example:
                errores:
                - codigo: "401.1"
                  mensaje: "Acceso no autorizado, x-api-key no válida."
                - codigo: "401.2"
                  mensaje: Acceso no autorizado.
                - codigo: "401.3"
                  mensaje: "Acceso no autorizado, no tiene el producto asociado."
                - codigo: "401.4"
                  mensaje: "Acceso no autorizado, no tiene acceso al recurso."
              schema:
                $ref: "#/components/schemas/Errores"
          description: Unauthorized
        "403":
          content:
            application/json:
              example:
                errores:
                - codigo: "403"
                  mensaje: Acceso denegado
                - codigo: "403.1"
                  mensaje: "No se pudo autenticar, x-signature no es válida."
                - codigo: "403.2"
                  mensaje: No se pudo autenticar.
              schema:
                $ref: "#/components/schemas/Errores"
          description: FORBIDDEN
        "404":
          content:
            application/json:
              example:
                errores:
                - codigo: "404.1"
                  mensaje: No se encontró a la persona.
              schema:
                $ref: "#/components/schemas/Errores"
          description: NOT FOUND
        "405":
          content:
            application/json:
              example:
                errores:
                - codigo: "405.1"
                  mensaje: Método no permitido.
              schema:
                $ref: "#/components/schemas/Errores"
          description: METHOD NOT ALLOWED
        "415":
          content:
            application/json:
              example:
                errores:
                - codigo: "415.1"
                  mensaje: Medios no admitidos
              schema:
                $ref: "#/components/schemas/Errores"
          description: UNSUPPORTED MEDIA TYPE.
        "429":
          content:
            application/json:
              example:
                errores:
                - codigo: "429.1"
                  mensaje: Se han enviado demasiadas solicitudes. Se debe esperar
                    antes de realizar una nueva solicitud.
              schema:
                $ref: "#/components/schemas/Errores"
          description: TOO MANY REQUESTS
        "500":
          content:
            application/json:
              example:
                errores:
                - codigo: "500"
                  mensaje: Ocurrio un error al procesar tu solicitud.
                - codigo: "500.1"
                  mensaje: "Ocurrio un problema, inténtelo nuevamente más tarde."
              schema:
                $ref: "#/components/schemas/Errores"
          description: INTERNAL SERVER ERROR
        "503":
          content:
            application/json:
              example:
                errores:
                - codigo: "503.1"
                  mensaje: Servicio no disponible.
              schema:
                $ref: "#/components/schemas/Errores"
          description: SERVICE UNAVAILABLE
      summary: ""
      tags:
      - Score Datos Generales
      x-codegen-request-body-name: ScoreDG
      x-content-type: application/json
      x-accepts:
      - application/json
  /folio:
    post:
      deprecated: false
      description: ""
      operationId: /folio
      parameters:
      - description: Firma generada con la llave privada
        explode: false
        in: header
        name: x-signature
        required: true
        schema:
          type: string
        style: simple
      - description: ConsumerKey obtenido desde el portal de desarrolladores
        explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - description: Usuario de Círculo de Crédito
        explode: false
        in: header
        name: username
        required: true
        schema:
          type: string
        style: simple
      - description: Contraseña de Círculo de Crédito
        explode: false
        in: header
        name: password
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestScoreFolio"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseScore"
          description: OK
        "204":
          content: {}
          description: NO CONTENT
        "400":
          content:
            application/json:
              example:
                errores:
                - codigo: "400"
                  mensaje: "El campo [nombre_campo] es requerido"
                - codigo: "400"
                  mensaje: El código postal no corresponde al estado.
                - codigo: "400.4"
                  mensaje: Petición incorrecta el x-signature es requerido.
              schema:
                $ref: "#/components/schemas/Errores"
          description: BAD REQUEST
        "401":
          content:
            application/json:
              example:
                errores:
                - codigo: "401.1"
                  mensaje: "Acceso no autorizado, x-api-key no válida."
                - codigo: "401.2"
                  mensaje: Acceso no autorizado.
                - codigo: "401.3"
                  mensaje: "Acceso no autorizado, no tiene el producto asociado."
                - codigo: "401.4"
                  mensaje: "Acceso no autorizado, no tiene acceso al recurso."
              schema:
                $ref: "#/components/schemas/Errores"
          description: Unauthorized
        "403":
          content:
            application/json:
              example:
                errores:
                - codigo: "403"
                  mensaje: Acceso denegado
                - codigo: "403.1"
                  mensaje: "No se pudo autenticar, x-signature no es válida."
                - codigo: "403.2"
                  mensaje: No se pudo autenticar.
              schema:
                $ref: "#/components/schemas/Errores"
          description: FORBIDDEN
        "404":
          content:
            application/json:
              example:
                errores:
                - codigo: "404.1"
                  mensaje: No se encontró el Folio.
              schema:
                $ref: "#/components/schemas/Errores"
          description: NOT FOUND
        "405":
          content:
            application/json:
              example:
                errores:
                - codigo: "405.1"
                  mensaje: Método no permitido.
              schema:
                $ref: "#/components/schemas/Errores"
          description: METHOD NOT ALLOWED
        "415":
          content:
            application/json:
              example:
                errores:
                - codigo: "415.1"
                  mensaje: Medios no admitidos
              schema:
                $ref: "#/components/schemas/Errores"
          description: UNSUPPORTED MEDIA TYPE.
        "429":
          content:
            application/json:
              example:
                errores:
                - codigo: "429.1"
                  mensaje: Se han enviado demasiadas solicitudes. Se debe esperar
                    antes de realizar una nueva solicitud.
              schema:
                $ref: "#/components/schemas/Errores"
          description: TOO MANY REQUESTS
        "500":
          content:
            application/json:
              example:
                errores:
                - codigo: "500"
                  mensaje: Ocurrio un error al procesar tu solicitud.
                - codigo: "500.1"
                  mensaje: "Ocurrio un problema, inténtelo nuevamente más tarde."
              schema:
                $ref: "#/components/schemas/Errores"
          description: INTERNAL SERVER ERROR
        "503":
          content:
            application/json:
              example:
                errores:
                - codigo: "503.1"
                  mensaje: Servicio no disponible.
              schema:
                $ref: "#/components/schemas/Errores"
          description: SERVICE UNAVAILABLE
      summary: ""
      tags:
      - ScoreFolio
      x-codegen-request-body-name: ScoreFolio
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    CatalogoEstados:
      description: Estado en que se ubica el domicilio <table><thead><tr><th>Clave</th><th>Estado</th></tr></thead><tbody><tr><td>AGS</td><td>AGUASCALIENTES</td></tr><tr><td>BCN</td><td>BAJA
        CALIFORNIA NORTE</td></tr><tr><td>BCS</td><td>BAJA CALIFORNIA SUR</td></tr><tr><td>CAM</td><td>CAMPECHE</td></tr><tr><td>CHS</td><td>CHIAPAS</td></tr><tr><td>CHI</td><td>CHIHUAHUA</td></tr><tr><td>COA</td><td>COHAHUILA</td></tr><tr><td>COL</td><td>COLIMA</td></tr><tr><td>DF</td><td>DISTRITO
        FEDERAL</td></tr><tr><td>DGO</td><td>DURANGO</td></tr><tr><td>EM</td><td>ESTADO
        DE MEXICO</td></tr><tr><td>GTO</td><td>GUANAJUATO</td></tr><tr><td>GRO</td><td>GUERRERO</td></tr><tr><td>HGO</td><td>HIDALGO</td></tr><tr><td>JAL</td><td>JALISCO</td></tr><tr><td>MICH</td><td>MICHOCÁN</td></tr><tr><td>MOR</td><td>MORELOS</td></tr><tr><td>NAY</td><td>NAYARIT</td></tr><tr><td>NL</td><td>NUEVO
        LEÓN</td></tr><tr><td>OAX</td><td>OAXACA</td></tr><tr><td>PUE</td><td>PUEBLA</td></tr><tr><td>QRO</td><td>QUERÉTARO</td></tr><tr><td>QR</td><td>QUINTANA
        ROO</td></tr><tr><td>SLP</td><td>SAN LUIS POTOSÍ</td></tr><tr><td>SIN</td><td>SINALOA</td></tr><tr><td>SON</td><td>SONORA</td></tr><tr><td>TAB</td><td>TABASCO</td></tr><tr><td>TAM</td><td>TAMAULIPAS</td></tr><tr><td>TLAX</td><td>TLAXCALA</td></tr><tr><td>VER</td><td>VERACRUZ</td></tr><tr><td>YUC</td><td>YUCATÁN</td></tr><tr><td>ZAC</td><td>ZACATECAS</td></tr></tbody></table>
      enum:
      - AGS
      - BCN
      - BCS
      - CAMP
      - COAH
      - COL
      - CHIS
      - CHIH
      - DF
      - DGO
      - GTO
      - GRO
      - HGO
      - JAL
      - MEX
      - MICH
      - MOR
      - NAY
      - NL
      - OAX
      - PUE
      - QRO
      - QROO
      - SLP
      - SIN
      - SON
      - TAB
      - TAMP
      - TLAX
      - VER
      - YUC
      - ZAC
      - CDMX
      example: DF
      type: string
    CatalogoTipoAsentamiento:
      description: <table><thead><tr><th>Clave</th><th>Tipo de Asentamiento</th></tr></thead><tbody><tr><td>0</td><td>PENDIENTE
        POR ACTUALIZAR</td></tr><tr><td>1</td><td>AEROPUERTO</td></tr><tr><td>2</td><td>BARRIO</td></tr><tr><td>3</td><td>BASE
        NAVAL</td></tr><tr><td>4</td><td>CAMPAMENTO</td></tr><tr><td>5</td><td>CENTRO</td></tr><tr><td>6</td><td>CENTRO
        URBANO</td></tr><tr><td>7</td><td>COLONIA</td></tr><tr><td>8</td><td>CONDOMINIO</td></tr><tr><td>9</td><td>CONGREGACION</td></tr><tr><td>10</td><td>CONJUNTO
        HABITACIONAL</td></tr><tr><td>11</td><td>CONJUNTO HABITACIONAL RESIDENCIAL</td></tr><tr><td>12</td><td>CONJUNTO
        HABITACIONAL URBANO</td></tr><tr><td>13</td><td>CONJUNTO POPULAR</td></tr><tr><td>14</td><td>CONJUNTO
        RESIDENCIAL</td></tr><tr><td>15</td><td>CONJUNTO URBANO</td></tr><tr><td>16</td><td>CONJUNTO
        URBANO POPULAR</td></tr><tr><td>17</td><td>EJIDO</td></tr><tr><td>18</td><td>ESCUELA</td></tr><tr><td>19</td><td>ESTACION
        DE RADIO</td></tr><tr><td>20</td><td>EX-HACIENDA</td></tr><tr><td>21</td><td>EX-RANCHO</td></tr><tr><td>22</td><td>FABRICA</td></tr><tr><td>23</td><td>FINCA</td></tr><tr><td>24</td><td>FRACCIONAMIENTO</td></tr><tr><td>25</td><td>FRACCIONAMIENTO
        INDUSTRIAL</td></tr><tr><td>26</td><td>FRACCIONAMIENTO RESIDENCIAL</td></tr><tr><td>27</td><td>GRANJA</td></tr><tr><td>28</td><td>HACIENDA</td></tr><tr><td>29</td><td>INGENIO</td></tr><tr><td>30</td><td>JUNTA
        AUXILIA</td></tr><tr><td>31</td><td>MODULO HABIT</td></tr><tr><td>32</td><td>PARQUE</td></tr><tr><td>33</td><td>PARQUE
        INDUS</td></tr><tr><td>34</td><td>CUADRILLA</td></tr><tr><td>35</td><td>POBLADO
        COM</td></tr><tr><td>36</td><td>PUEBLO</td></tr><tr><td>37</td><td>RANCHO
        O RAN</td></tr><tr><td>38</td><td>RESIDENCIAL</td></tr><tr><td>39</td><td>VILLA</td></tr><tr><td>40</td><td>UNIDAD
        HABIT</td></tr><tr><td>41</td><td>ZONA FEDERAL</td></tr><tr><td>42</td><td>ZONA
        HABITAC</td></tr><tr><td>43</td><td>ZONA INDUSTR</td></tr><tr><td>44</td><td>ZONA
        RESIDEN</td></tr><tr><td>45</td><td>ZONA URBANA</td></tr><tr><td>46</td><td>ZONA
        URBANA</td></tr><tr><td>47</td><td>CAMPO MILITA</td></tr><tr><td>48</td><td>VIVIENDA
        POPU</td></tr><tr><td>49</td><td>CLUB DE GOLF</td></tr><tr><td>50</td><td>COOPERATIVA</td></tr><tr><td>51</td><td>CIUDAD</td></tr><tr><td>52</td><td>OFICINA
        DE CO</td></tr><tr><td>53</td><td>GRAN USUARIO</td></tr><tr><td>54</td><td>ZONA
        COMERC</td></tr><tr><td>55</td><td>ZONA RURAL</td></tr></tbody></table>
      enum:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "35"
      - "36"
      - "37"
      - "38"
      - "39"
      - "40"
      - "41"
      - "42"
      - "43"
      - "44"
      - "45"
      - "46"
      - "47"
      - "48"
      - "49"
      - "50"
      - "51"
      - "52"
      - "53"
      - "54"
      - "55"
      example: "28"
      type: string
    CatalogoTipoDomicilio:
      description: <table><thead><tr><th>Clave</th><th>Descripción</th></tr></thead><tbody><tr><td>N</td><td>Negocio</td></tr><tr><td>O</td><td>Domicilio
        del otorgante</td></tr><tr><td>C</td><td>Casa</td></tr><tr><td>P</td><td>Apartado
        Postal</td></tr><tr><td>E</td><td>Empleo</td></tr></tbody></table>
      enum:
      - "N"
      - O
      - C
      - P
      - E
      example: C
      maxLength: 1
      minLength: 1
      type: string
    RequestScoreDG:
      description: Cuerpo de la petición para obtener respuesta del servicio
      example:
        persona:
          apellidoPaterno: Prueba
          segundoNombre: segundoNombre
          fechaDefuncion: fechaDefuncion
          fechaNacimiento: 1980-01-04
          numeroDependientes: numeroDependientes
          residencia: residencia
          claveElectorIFE: claveElectorIFE
          apellidoAdicional: apellidoAdicional
          estadoCivil: estadoCivil
          RFC: PUSJ800104H2O
          nombres: Juan
          apellidoMaterno: Cuatro
          CURP: CURP
          nacionalidad: nacionalidad
          domicilio:
            estado: DF
            direccion: INSURGENTES SUR 1004
            fechaRegistroDomicilio: 2018-12-20
            CP: "11230"
            idDomicilio: "316110890"
            tipoAltaDomicilio: 1
            delegacionMunicipio: BENITO JUAREZ
            ciudad: CIUDAD DE MÉXICO
            fechaResidencia: fechaResidencia
            tipoDomicilio: C
            coloniaPoblacion: INSURGENTES
            numeroTelefono: numeroTelefono
            tipoAsentamiento: "28"
          sexo: sexo
        folio: 1736967881
      properties:
        folio:
          $ref: "#/components/schemas/RequestScoreDG_folio"
        persona:
          $ref: "#/components/schemas/RequestScoreDG_persona"
      required:
      - folio
      - persona
      type: object
    Domicilio:
      description: Datos del domicilio de la persona a consultar
      example:
        estado: DF
        direccion: INSURGENTES SUR 1004
        fechaRegistroDomicilio: 2018-12-20
        CP: "11230"
        idDomicilio: "316110890"
        tipoAltaDomicilio: 1
        delegacionMunicipio: BENITO JUAREZ
        ciudad: CIUDAD DE MÉXICO
        fechaResidencia: fechaResidencia
        tipoDomicilio: C
        coloniaPoblacion: INSURGENTES
        numeroTelefono: numeroTelefono
        tipoAsentamiento: "28"
      properties:
        direccion:
          description: "Reportar el nombre de la calle, número exterior, número interior.\
            \ Deben considerarse avenida,cerrada, manzana, lote, edificio,departamento\
            \ etc. Debe contener por lo menos dos cadenas de caracteres para que el\
            \ registro sea válido, de lo contrario el registro será rechazado."
          example: INSURGENTES SUR 1004
          minLength: 1
          type: string
        coloniaPoblacion:
          description: Reportar la colonia a la cual pertenece la dirección contenida
            en el elemento dirección.
          example: INSURGENTES
          minLength: 1
          type: string
        delegacionMunicipio:
          description: Reportar la delegación o municipio a la cual pertenece la dirección
            contenida en el elemento Dirección.
          example: BENITO JUAREZ
          minLength: 1
          type: string
        ciudad:
          description: Reportar la ciudad a la cual pertenece la dirección contenida
            en el elemento Dirección.
          example: CIUDAD DE MÉXICO
          minLength: 1
          type: string
        estado:
          $ref: "#/components/schemas/CatalogoEstados"
        CP:
          description: El código postal reportado debe estar compuesto por 5 dígitos.
            Para que el código postal sea válido deberá corresponder al estado reportado.
          example: "11230"
          maxLength: 5
          minLength: 5
          type: string
        fechaResidencia:
          nullable: true
          type: string
        numeroTelefono:
          nullable: true
          type: string
        tipoDomicilio:
          $ref: "#/components/schemas/CatalogoTipoDomicilio"
        tipoAsentamiento:
          $ref: "#/components/schemas/CatalogoTipoAsentamiento"
        fechaRegistroDomicilio:
          description: Fecha en la cual se registró el domicilio.
          example: 2018-12-20
          nullable: true
          type: string
        tipoAltaDomicilio:
          description: "Los valores posibles: 0 = Alta de crédito 1 = Consulta expediente"
          example: 1
          nullable: true
          type: number
        idDomicilio:
          description: Identificador único del domicilio
          example: "316110890"
          nullable: true
          type: string
      required:
      - CP
      - ciudad
      - coloniaPoblacion
      - delegacionMunicipio
      - direccion
      - estado
      type: object
    Error:
      description: error
      example:
        codigo: "400.1"
        mensaje: "El campo \"{Campo}\" es requerido."
      properties:
        codigo:
          description: Código de error.
          example: "400.1"
          type: string
        mensaje:
          description: Mensaje de error.
          example: "El campo \"{Campo}\" es requerido."
          type: string
      type: object
    Errores:
      description: "Si existen errores, se listarán."
      example:
        errores:
        - codigo: "400.1"
          mensaje: "El campo \"{Campo}\" es requerido."
        - codigo: "400.1"
          mensaje: "El campo \"{Campo}\" es requerido."
      properties:
        errores:
          items:
            $ref: "#/components/schemas/Error"
          type: array
      type: object
    RequestScoreFolio:
      description: Cuerpo de la petición para obtener respuesta del servicio
      example:
        folioOtorgante: "1234"
        folioConsulta: "390038369"
      properties:
        folioConsulta:
          example: "390038369"
          maxLength: 50
          pattern: "^([0-9]){0,15}$"
          type: string
        folioOtorgante:
          example: "1234"
          maxLength: 50
          pattern: "^([A-Za-z0-9]){0,50}$"
          type: string
      required:
      - folioConsulta
      - folioOtorgante
      type: object
    ResponseScore:
      description: Si existen información se entregara en esta estructura de datos.
      example:
        score:
          nombreScore: FICO
          valor: 482
          razones:
          - K0
          - J0
          - E2
          - D8
        folio: "123"
        folioConsulta: "324567279"
      properties:
        folio:
          example: "123"
          maxLength: 25
          type: string
        folioConsulta:
          example: "324567279"
          maxLength: 50
          pattern: "^([A-Za-z0-9]){0,50}$"
          type: string
        score:
          $ref: "#/components/schemas/ResponseScore_score"
      type: object
    RequestScoreDG_folio:
      example: 1736967881
      maxLength: 25
      oneOf:
      - type: string
      - type: integer
    RequestScoreDG_persona:
      example:
        apellidoPaterno: Prueba
        segundoNombre: segundoNombre
        fechaDefuncion: fechaDefuncion
        fechaNacimiento: 1980-01-04
        numeroDependientes: numeroDependientes
        residencia: residencia
        claveElectorIFE: claveElectorIFE
        apellidoAdicional: apellidoAdicional
        estadoCivil: estadoCivil
        RFC: PUSJ800104H2O
        nombres: Juan
        apellidoMaterno: Cuatro
        CURP: CURP
        nacionalidad: nacionalidad
        domicilio:
          estado: DF
          direccion: INSURGENTES SUR 1004
          fechaRegistroDomicilio: 2018-12-20
          CP: "11230"
          idDomicilio: "316110890"
          tipoAltaDomicilio: 1
          delegacionMunicipio: BENITO JUAREZ
          ciudad: CIUDAD DE MÉXICO
          fechaResidencia: fechaResidencia
          tipoDomicilio: C
          coloniaPoblacion: INSURGENTES
          numeroTelefono: numeroTelefono
          tipoAsentamiento: "28"
        sexo: sexo
      properties:
        nombres:
          example: Juan
          maxLength: 30
          pattern: "[A-Za-z0-9 àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸç\
            ÇßØøÅåÆæœ]+"
          type: string
        segundoNombre:
          maxLength: 30
          nullable: true
          pattern: "[A-Za-z0-9 àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸç\
            ÇßØøÅåÆæœ]+"
          type: string
          example: null
        apellidoPaterno:
          example: Prueba
          maxLength: 30
          pattern: "[A-Za-z0-9 àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸç\
            ÇßØøÅåÆæœ]+"
          type: string
        apellidoMaterno:
          example: Cuatro
          maxLength: 30
          pattern: "[A-Za-z0-9 àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸç\
            ÇßØøÅåÆæœ]+"
          type: string
        apellidoAdicional:
          maxLength: 30
          nullable: true
          pattern: "[A-Za-z0-9 àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸç\
            ÇßØøÅåÆæœ]+"
          type: string
          example: null
        fechaNacimiento:
          example: 1980-01-04
          type: string
        RFC:
          example: PUSJ800104H2O
          type: string
        CURP:
          nullable: true
          type: string
          example: null
        nacionalidad:
          type: string
        residencia:
          nullable: true
          type: string
        estadoCivil:
          nullable: true
          type: string
        sexo:
          nullable: true
          type: string
        claveElectorIFE:
          nullable: true
          type: string
        numeroDependientes:
          nullable: true
          type: string
        fechaDefuncion:
          nullable: true
          type: string
        domicilio:
          $ref: "#/components/schemas/Domicilio"
      required:
      - apellidoMaterno
      - apellidoPaterno
      - domicilio
      - fechaNacimiento
      - nombres
      type: object
    ResponseScore_score:
      example:
        nombreScore: FICO
        valor: 482
        razones:
        - K0
        - J0
        - E2
        - D8
      properties:
        nombreScore:
          type: string
        valor:
          type: integer
        razones:
          items:
            type: string
          type: array
      type: object

